CREATE DATABASE financial_db;

USE financial_db;

-- Income Statement Tables
CREATE TABLE income_statement_annual (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(10),
    fiscal_date_ending VARCHAR(20),
    reported_currency VARCHAR(10),
    gross_profit INT,
    total_revenue INT,
    cost_of_revenue INT,
    cost_of_goods_and_services_sold INT,
    operating_income INT,
    selling_general_and_administrative INT,
    research_and_development INT,
    operating_expenses INT,
    investment_income_net INT,
    net_interest_income INT,
    interest_income INT,
    interest_expense INT,
    non_interest_income INT,
    other_non_operating_income INT,
    depreciation INT,
    depreciation_and_amortization INT,
    income_before_tax INT,
    income_tax_expense INT,
    interest_and_debt_expense INT,
    net_income_from_continuing_operations INT,
    comprehensive_income_net_of_tax INT,
    ebit INT,
    ebitda INT,
    net_income INT,
    UNIQUE(symbol, fiscal_date_ending)
);

CREATE TABLE income_statement_quarter (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(10),
    fiscal_date_ending VARCHAR(20),
    reported_currency VARCHAR(10),
    gross_profit INT,
    total_revenue INT,
    cost_of_revenue INT,
    cost_of_goods_and_services_sold INT,
    operating_income INT,
    selling_general_and_administrative INT,
    research_and_development INT,
    operating_expenses INT,
    investment_income_net INT,
    net_interest_income INT,
    interest_income INT,
    interest_expense INT,
    non_interest_income INT,
    other_non_operating_income INT,
    depreciation INT,
    depreciation_and_amortization INT,
    income_before_tax INT,
    income_tax_expense INT,
    interest_and_debt_expense INT,
    net_income_from_continuing_operations INT,
    comprehensive_income_net_of_tax INT,
    ebit INT,
    ebitda INT,
    net_income INT,
    UNIQUE(symbol, fiscal_date_ending)
);

CREATE TABLE balance_sheet_annual (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(10),
    fiscal_date_ending VARCHAR(20),
    reported_currency VARCHAR(10),
    total_assets INT,
    total_current_assets INT,
    cash_and_cash_equivalents INT,
    cash_and_short_term_investments INT,
    inventory INT,
    current_net_receivables INT,
    total_non_current_assets INT,
    property_plant_equipment INT,
    accumulated_depreciation_amortization_ppe INT,
    intangible_assets INT NULL,
    intangible_assets_excluding_goodwill INT NULL,
    goodwill INT NULL,
    investments INT,
    long_term_investments INT,
    short_term_investments INT,
    other_current_assets INT,
    other_non_current_assets INT,
    total_liabilities INT,
    total_current_liabilities INT,
    current_accounts_payable INT,
    deferred_revenue INT NULL,
    current_debt INT NULL,
    short_term_debt INT,
    total_non_current_liabilities INT,
    capital_lease_obligations INT NULL,
    long_term_debt INT,
    current_long_term_debt INT,
    long_term_debt_noncurrent INT,
    short_long_term_debt_total INT,
    other_current_liabilities INT,
    other_non_current_liabilities INT,
    total_shareholder_equity INT,
    treasury_stock INT NULL,
    retained_earnings INT,
    common_stock INT,
    common_stock_shares_outstanding INT,
    UNIQUE(symbol, fiscal_date_ending)
);

CREATE TABLE balance_sheet_quarter (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(10),
    fiscal_date_ending VARCHAR(20),
    reported_currency VARCHAR(10),
    total_assets INT,
    total_current_assets INT,
    cash_and_cash_equivalents INT,
    cash_and_short_term_investments INT,
    inventory INT,
    current_net_receivables INT,
    total_non_current_assets INT,
    property_plant_equipment INT,
    accumulated_depreciation_amortization_ppe INT,
    intangible_assets INT NULL,
    intangible_assets_excluding_goodwill INT NULL,
    goodwill INT NULL,
    investments INT,
    long_term_investments INT,
    short_term_investments INT,
    other_current_assets INT,
    other_non_current_assets INT,
    total_liabilities INT,
    total_current_liabilities INT,
    current_accounts_payable INT,
    deferred_revenue INT NULL,
    current_debt INT NULL,
    short_term_debt INT,
    total_non_current_liabilities INT,
    capital_lease_obligations INT NULL,
    long_term_debt INT,
    current_long_term_debt INT,
    long_term_debt_noncurrent INT,
    short_long_term_debt_total INT,
    other_current_liabilities INT,
    other_non_current_liabilities INT,
    total_shareholder_equity INT,
    treasury_stock INT NULL,
    retained_earnings INT,
    common_stock INT,
    common_stock_shares_outstanding INT,
    UNIQUE(symbol, fiscal_date_ending)
);


-- cash flow
CREATE TABLE cash_flow_annual (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(10),
    fiscal_date_ending VARCHAR(20),
    reported_currency VARCHAR(10),
    operating_cashflow INT,
    payments_for_operating_activities INT NULL,
    proceeds_from_operating_activities INT NULL,
    change_in_operating_liabilities INT NULL,
    change_in_operating_assets INT NULL,
    depreciation_depletion_and_amortization INT,
    capital_expenditures INT,
    change_in_receivables INT,
    change_in_inventory INT,
    profit_loss INT,
    cashflow_from_investment INT,
    cashflow_from_financing INT,
    proceeds_from_repayments_of_short_term_debt INT NULL,
    payments_for_repurchase_of_common_stock INT,
    payments_for_repurchase_of_equity INT,
    payments_for_repurchase_of_preferred_stock INT NULL,
    dividend_payout INT,
    proceeds_from_issuance_of_common_stock INT NULL,
    proceeds_from_issuance_of_long_term_debt INT NULL,
    change_in_cash_and_cash_equivalents INT NULL,
    net_income INT,
    UNIQUE(symbol, fiscal_date_ending)
);

CREATE TABLE cash_flow_quarter (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(10),
    fiscal_date_ending VARCHAR(20),
    reported_currency VARCHAR(10),
    operating_cashflow INT,
    payments_for_operating_activities INT NULL,
    proceeds_from_operating_activities INT NULL,
    change_in_operating_liabilities INT NULL,
    change_in_operating_assets INT NULL,
    depreciation_depletion_and_amortization INT,
    capital_expenditures INT,
    change_in_receivables INT,
    change_in_inventory INT,
    profit_loss INT,
    cashflow_from_investment INT,
    cashflow_from_financing INT,
    proceeds_from_repayments_of_short_term_debt INT NULL,
    payments_for_repurchase_of_common_stock INT,
    payments_for_repurchase_of_equity INT,
    payments_for_repurchase_of_preferred_stock INT NULL,
    dividend_payout INT,
    proceeds_from_issuance_of_common_stock INT NULL,
    proceeds_from_issuance_of_long_term_debt INT NULL,
    change_in_cash_and_cash_equivalents INT NULL,
    net_income INT,
    UNIQUE(symbol, fiscal_date_ending)
);

CREATE TABLE company (
    symbol VARCHAR(10) PRIMARY KEY,
    asset_type VARCHAR(50),
    name VARCHAR(255),
    description TEXT,
    cik VARCHAR(20),
    exchange VARCHAR(50),
    currency VARCHAR(10),
    country VARCHAR(50),
    sector VARCHAR(50),
    industry VARCHAR(100),
    address TEXT,
    official_site VARCHAR(255),
    fiscal_year_end VARCHAR(20),
    next_earning_report DATE
);